<?php
/**
 * Kalin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to kalinvadim@gmail.com so we can send you a copy immediately.
 *
 * @category  Kalin
 * @package   Kalin_GoogleKnowledgeGraph
 * @link      https://github.com/VadymKalin/magento-google-knowledge-graph
 * @author    Vadym Kalin <kalinvadim@gmail.com>
 * @copyright Copyright (c) 2015-2016 Vadym Kalin (http://full-stack-dev.com)
 * @license   http://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<?php
$_helper = $this->helper('googleknowledgegraph');
$_baseUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
?>
<?php if (!$this->helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <!-- BEGIN GOOGLE KNOWLEDGE GRAPH -->
    <script type="application/ld+json">
    {
        "@context" : "http://schema.org",
        "@type" : "Organization",
        "url" : "<?php echo $_baseUrl; ?>",
        "logo" : "<?php echo $this->_getLogoUrl(); ?>",
        "sameAs" : [
            <?php echo $this->_getSocialLinks(); ?>],
        "contactPoint" : [{
           "@type" : "ContactPoint",
           "telephone" : "<?php echo $_helper->getTelephone(); ?>",
           "contactType" : "<?php echo $_helper->getContactType(); ?>",
           "contactOption" : "<?php echo $_helper->getContactOption(); ?>",
           "areaServed" : [
                "US"
           ],
           "availableLanguage" : [
                "<?php echo $_helper->getAvailableLanguage(); ?>",
           ]
        }]
    }
    </script>
    <!-- END GOOGLE KNOWLEDGE GRAPH -->
<?php endif; ?>
